
services:
  db:
    image: postgres:16
    container_name: events_pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: eventsdb
      POSTGRES_USER: eventsuser
      POSTGRES_PASSWORD: supersecret
    ports:
      - "5432:5432"
    volumes:
      - events_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eventsuser -d eventsdb"]
      interval: 5s
      timeout: 3s
      retries: 10